[window]
padding = { x = 5, y = 2 }
startup_mode = "Maximized"
title = "alacritty"
dynamic_title = false
 
[font]
normal = { family = "JetBrains Mono", style = "SemiBold" }
size = 12
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
 
[cursor]
thickness = 0.20
 
[colors.primary]
background = '#181616'
foreground = '#c5c9c5'
 
[colors.normal]
black = '#0d0c0c'
blue = '#8ba4b0'
cyan = '#8ea4a2'
green = '#8a9a7b'
magenta = '#a292a3'
red = '#c4746e'
white = '#C8C093'
yellow = '#c4b28a'
 
[colors.bright]
black = '#a6a69c'
blue = '#7FB4CA'
cyan = '#7AA89F'
green = '#87a987'
magenta = '#938AA9'
red = '#E46876'
white = '#c5c9c5'
yellow = '#E6C384'
 
[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'
 
[[colors.indexed_colors]]
index = 16
color = '#ffa066'
 
[[colors.indexed_colors]]
index = 17
color = '#ff5d62'
 
#[colors.cursor]
#text = '#282828'
#cursor = '#d5c4a1'
#
#[colors.primary]
#background = '#282828'
#foreground = '#ebdbb2'
#
#[colors.normal]
#black   = '#282828'
#red     = '#cc241d'
#green   = '#98971a'
#yellow  = '#d79921'
#blue    = '#458588'
#magenta = '#b16286'
#cyan    = '#689d6a'
#white   = '#a89984'
#
#[colors.bright]
#black   = '#928374'
#red     = '#fb4934'
#green   = '#b8bb26'
#yellow  = '#fabd2f'
#blue    = '#83a598'
#magenta = '#d3869b'
#cyan    = '#8ec07c'
#white   = '#ebdbb2'
#
#[colors]
#indexed_colors = [
#  { index = 16, color = '#fe8019'},
#  { index = 17, color = '#d65d0e'},
#  { index = 18, color = '#3c3836'},
#  { index = 19, color = '#504945'},
#  { index = 20, color = '#bdae93'},
#  { index = 21, color = '#ebdbb2'},
#]
