#! /bin/sh

xrandr --output Virtual-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
feh --bg-fill ~/desktop-wallpaper-1.png
udiskie -ans &
dunst &

bspc monitor Virtual-1 -d 1 2 3 4 5

bspc config border_width         4
bspc config window_gap           5
bspc config focused_border_color "#D65D0E"
bspc config normal_border_color  "#3C3836"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config pointer_follows_focus false

bspc rule -a mpv state=floating center=on
bspc rule -a Xfce4-terminal state=floating
