config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
    link: link
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
    link: link
  f_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
    link: link
  d_bat:
    src: config/bat
    dst: ~/.config/bat
    link: link
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
    link: link
  f_picom.conf:
    src: config/picom/picom.conf
    dst: ~/.config/picom/picom.conf
    link: link
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
    link: link
  f_vifmrc:
    src: config/vifm/vifmrc
    dst: ~/.config/vifm/vifmrc
    link: link
  d_pixelfun3:
    src: icons/pixelfun3
    dst: ~/.icons/pixelfun3
    link: link
  f_conkyrc:
    src: conkyrc
    dst: ~/.conkyrc
    link: link
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    link: link
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
    link: link
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    link: link
  f_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
    link: link
  f_fzf.vim:
    src: config/nvim/fzf.vim
    dst: ~/.config/nvim/fzf.vim
    link: link
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
    link: link
  f_startify-bookmarks.vim:
    src: config/nvim/startify-bookmarks.vim
    dst: ~/.config/nvim/startify-bookmarks.vim
    link: link
  f_my-theme.zsh-theme:
    src: oh-my-zsh/custom/themes/my-theme.zsh-theme
    dst: ~/.oh-my-zsh/custom/themes/my-theme.zsh-theme
    link: link
profiles:
  home:
    dotfiles:
    - f_config
    - d_polybar
    - f_kitty.conf
    - d_bat
    - d_dunst
    - f_picom.conf
    - d_rofi
    - f_vifmrc
    - d_pixelfun3
    - f_conkyrc
    - f_tmux.conf
    - f_xinitrc
    - f_zshrc
    - f_coc-settings.json
    - f_fzf.vim
    - f_init.vim
    - f_startify-bookmarks.vim
    - f_my-theme.zsh-theme
