#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
xinput --set-prop 14 'libinput Accel Speed' -0.8
feh --bg-fill $HOME/Images/fon2.jpg --bg-fill $HOME/Images/wall.png
xfce4-power-manager &
udiskie -ans &
dunst &

bspc monitor -d 1 2 3 4 5

bspc config border_width         4
bspc config window_gap          10
bspc config focused_border_color "#458588"
bspc config normal_border_color "#504945"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Osmo state=floating center=on
bspc rule -a mpv state=floating center=on
