#!/bin/bash

option_reboot="reboot"
option_shutdown="shutdown"

if [ x"$@" = x"$option_reboot" ]
then
  systemctl reboot;
fi

if [ x"$@" = x"$option_shutdown" ]
then
  systemctl poweroff;
fi

echo $option_reboot
echo $option_shutdown

